[경재] 숫자야구 구현
gonza-st/baseball-playground pull request #1
Opened 2024-12-10 04:35 UTC by gyeongjae-ham

- [x] 요구사항 정리
- [x] 숫자 야구 숫자 객체 생성 및 검증
- [x] 숫자 야구 게임 객체 생성 및 검증
- [x] 입,출력 구현
- [x] 게임 실행부 작성

2024-12-15 11:03 UTC, hongxeob requested changes
고생하셨습니다 경재님~ 몇가지 코멘트 남겨드렸습니다!
+ 현재는 패키지 구조없이 설정되어 있는데 패키지 구조까지 고민해 보시면 좋을 거 같습니다!

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +        Scanner scanner = new Scanner(System.in);
결과나 내용을 콘솔에 출력하는 클래스 같은데 입력을 받는 로직이 들어가 있는데 SRP 개념에서 보면 괜찮을까요?!

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +        } catch (Exception e) {
상위 개념의 Exception으로 캐치를 했을 때 문제는 없을까요?

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +        return isContinue;
isContinue 라는 이름만 들었을땐 boolean 타입인 것 같은데 실제론 int 타입으로 되어있는데, 처음 보는 개발자는 헷갈릴 수 있지 않을까요? 메서드 반환 타입도 int네요!

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +public class OutputView {
해당 클래스들의 메서드들은 모두 static으로 설정한 이유가 있을까요? 👀

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/test/java/org/gonza/javaplayground/FixNumberGenerator.java
> +}
해당 클래스는 왜 테스트 패키지에 있을까요?! 테스트용이라면 네이밍 or 패키지도 그렇게 가져가면 좋을거 같습니다.

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/test/java/org/gonza/javaplayground/BaseballGameTest.java
> +        FixNumberGenerator numberGenerator = new FixNumberGenerator();
`FixNumberGenerator numberGenerator = new FixNumberGenerator();`
중복되면 메서드화 하는것도 좋아보입니다!

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +public class BaseballGameNumber {
해당 클래스의 이름이 중의적 혹은 모호한 것 같아요. 그래서 해당 객체가 가진 책임과 역할이 많아 보이는 것 같기도..?

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/InputView.java
> +}
`숫자를 입력받는다()` 라는 네이밍의 메서드인데 안에는 print로 '출력' 하는 부분도 들어가 있어요. SRP에 위배되진 않을까요?

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    }
숫자를 받아서 -> String으로 변환 후 -> String을 잘라서 비교 후 -> 다시 숫자로 형 변환
숫자로 쭉 처리하지 않고 위와 같은 과정을 해줘야하는 이유가 있을까요? 타당한 이유라면 많은 역할을 하는거 같아요.

2024-12-15 11:03 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    }
private인데 static으로 띄워두는게 나을지 사용할 때 마다 생성하는게 나을지.. 뭐가 더 나을까유?

2024-12-17 03:54 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +public class OutputView {
굳이 instance화 되어야 쓸 수 있는 친구들일까 생각해봤습니다!

2024-12-17 03:59 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +public class BaseballGameNumber {
이 친구는 딱 숫자야구 게임이 숫자만 담당하고 있는 친구입니다 좀 더 명확하게 표현하려고 BaseballGameNumber라고 작성했는데 어떤 부분이 좀 모호해 보이실까요?

2024-12-17 04:00 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    }
ball인지 strike인지 확인하는 과정에서 해당 로직으로 하는게 더 간단하게 할 수 있다고 생각했습니다!

2024-12-17 04:01 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    }
생성자에서 쓰는거라서 static으로 했습니다!

2024-12-18 04:02 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    private int compareNumbers(char first, char second) {
값 비교에 대한 결과를 boolean이 아니라 int로 하신 이유가 있을까요 ? 1, 0 보다는 true, false로 같은 값인지 구분하는게 더 명확한 것 같습니다 !

2024-12-18 04:05 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    private int compareNumbers(char first, char second) {
여기 메소드를 사용하는 곳에서 count에 바로 더해주려고 했습니다 뭔가 의미없이 if 로 한번 더 처리하는 부분을 생략하려고 했던 것 같습니다

2024-12-18 04:11 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +            throw new IllegalArgumentException();
예외에 대해 텍스트가 필요해 보입니다.

2024-12-18 04:11 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/RandomNumberGenerator.java
> +    public BaseballGameNumber generate() {
현재 게임의 조건에는 부합하진 않지만,
자릿수가 늘어남에 따라 리소스 투입이 배수로 증가할 것 같다는 생각이 들었어요!

만약, 네 자리를 커버해야 한다면 모든 포지션 상수를 한 자리씩 증가할 것이고,
기능은 세 자리를 제공하지 못하게 될 것 같습니다.

`Random` 유틸의 특성을 잘 고민해보는 건 어떨까요?

2024-12-18 04:11 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +			baseballGame.init();
해당 게임 객체에서 시작과 종료에 대한 의미 표현이 모호해보입니다!
어떻게하면 잘 표현해 볼 수 있을까요?

2024-12-18 04:13 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +			baseballGame.init();
boolean 값으로 수정해서 명확하게 해보겠습니다!

2024-12-18 04:13 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		while (continueFlag == 1) {
continueFlag의 기본 설정값과, 비교 대상이 되는 값은 상수로 관리하는 것이 좋지 않을까요 ?

2024-12-18 04:13 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		if (strikeCount == 3) {
해당 부분도 3이 무슨 값을 의도하는 건지 바로 알기 어려운 것 같습니다. 상수로 관리하는 것은 어떨까요?

2024-12-18 04:17 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +            System.out.println(ballCount + "볼");
볼인 경우 아웃 메시지도 같이 출력되는 것은 아닐까요 ?

2024-12-18 04:20 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/RandomNumberGenerator.java
> +        int third = RANDOM.nextInt(NUMBER_RANGE) + CALIBRATE_NUMBER;
마지막 자리수를 생성하는 코드도 first, second와 마찬가지로 메소드화 하는 것이 일관된 코드를 제공하는데 좋지 않을까요 ?

2024-12-18 04:21 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/RandomNumberGenerator.java
> +        int third = RANDOM.nextInt(NUMBER_RANGE) + CALIBRATE_NUMBER;
+ POSITION의 값을 파라미터로 전달받는다면, 한 개의 메소드로 숫자를 생성할 수 있지 않을까요 ?

2024-12-18 04:45 UTC, gyungjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		while (continueFlag == 1) {
동일한 내용 리뷰 받은거랑 조합해서 수정하면 될 것 같습니다!

2024-12-18 04:46 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +            System.out.println(ballCount + "볼");
홀리 return이 빠졌군요 👍

2024-12-18 04:47 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +    private int compareNumbers(char first, char second) {
음 한번 더 생각해야 한다는 점에서 if문이 의미없지 않을 수도 있겠네요 공감했습니다

2024-12-18 05:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/RandomNumberGenerator.java
> +    public BaseballGameNumber generate() {
음 자리수 증가에 대한 고민에 대해 공감이 가는데  Random 유틸 특성과의 관계에 대해서는 어떤 연관성을 가지는지 좀 어렵네요 코드를 까봤는데 range를 설정해도 자릿수에 대한 해결책은 안되는 것 같아서요 혹시 어떤 부분을 생각하시고 주신 의견일까요? 자릿수를 제가 상수화하지 않고도 제어할 수 있는 걸까요?

2024-12-19 04:34 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +            return Integer.parseInt(inputNumber);
`BaseballGameNumber` 가 중복 검증 및 숫자야구의 범위 는 숫자야구 number 의 책임이 맞는 것 같은데 
`toNumber` 는 해당 객체의 책임은 아닌걸로 보입니다

2024-12-19 04:34 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +        if (ballCount > 0) {
`OutputView` 안에서 스트라이크 랑 볼에 대한 판단을 하는건 잘 모르겠네요 
단순히 출력만 하는 걸로 이해했는데 실제로 구현을 보니까 스트라이크 일때, 볼 일때를 판단하고 처리하는 것 같아서 (이건 제 생각임다)

2024-12-19 06:04 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/BaseballGameNumber.java
> +            return Integer.parseInt(inputNumber);
저는 생성자에서 숫자를 받기위한 검증 단계라고 생각했는데 어떠신가요?

2024-12-19 06:04 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +        if (ballCount > 0) {
0 일 경우 해당 부분은 출력하지 않아야 해서 분기처리하는 부분인데 좀 더 고민해보겠습니다!

2024-12-26 04:02 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/OutputView.java
> +        if (ballCount > 0) {
이 부분 볼 때 출력할 때 그냥 0이면 출력하지 않기 위한 코드인 것 같다고 느껴지긴 하네요 어떠신가요?

2025-01-04 08:58 UTC, hongxeob approved these changes

2025-01-06 09:00 UTC, merged