[홍섭] 숫자 야구
gonza-st/baseball-playground pull request #2
Opened 2024-12-11 01:03 UTC by hongxeob

# ⚾️ 숫자 야구 기능 목록 Check List

- [x] 1부터 9까지 서로 다른 랜덤 숫자 3개를 생성한다.
- [x] 사용자로부터 숫자를 입력 받는다.
    - [x] [예외] 받은 값이 3자리가 아니다.
    - [x] [예외] 받은 값이 숫자가 아니다.
    - [x] [예외] 받은 값에 중복이 있다.
- [x] 컴퓨터의 수 & 플레이어수를 비교한다.
    - [x] 몇 개의 숫자가 같은지 확인한다.
    - [x] 특정 자리에 해당 숫자가 있는지 확인한다.
        - [x] 같은 숫자만 있으면 `ball`
        - [x] 같은 숫자 + 같은 위치면 `strike`
        - [x] 같은 숫자가 하나도 없으면 `낫싱`
        - [x] 숫자 모두 같은 위치에 있으면 게임 종료.
- [x] 사용자에게 결과를 알려준다.
- [x] 재시작 여부를 묻는다.
    - [x] [예외] 1,2 이외의 값이 포함 되어있다.

2024-12-17 08:40 UTC, gyeongjae-ham requested changes
궁금한 점 몇 가지 남겼습니다👍

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +        Game game = new Game(numberGenerator, reader, judgement, printer);
여기에 명시되어 있지 않지만 reader, printer가 Game 안으로 들어가서 도메인 로직에 섞이지 않는 조건이 있습니다 홍섭님

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +    }
저희 객체지향 생활체조 들여쓰기 원칙에 맞춰서 리팩토링 되어야 할 것 같습니다 아마 출력 부분이 들어오면서 생긴 부분같습니다!

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/Judgement.java
> +    public String compareNumber(List<Integer> computerNumberList, List<Integer> playerNumberList) {
List<Number>는 의미를 가지는 객체가 될 수 있을 것처럼 보이는데 어떠신가요?

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/Judgement.java
> +    }
이 부분도 들여쓰기 같습니다

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +    }
askRetry도 그런것 같습니다!

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/Judgement.java
> +    }
getPlaceHitCount도 그런것 같습니다!

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/NumberGenerator.java
> +        Random random = new Random();
이 친구는 한번만 선언되고 쓸 수 있어 보이는데 어떠신가요?

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/core/NumberGenerator.java
> +        }
들여쓰기인 것 같습니다!

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/view/ConsoleReader.java
> +public class ConsoleReader implements Reader {
궁금해서 여쭤봅니다 인터페이스 - 구현으로 하신 이유가 있을까요?

2024-12-17 08:40 UTC, gyeongjae-ham commented on java-playground/src/test/java/org/gonza/javaplayground/core/GameTest.java
> +@ExtendWith(MockitoExtension.class)
TDD로 하는 연습에서는 목표가 Mockito 없이 개발하는 것도 목표라고 생각합니다. 이 과정에서 객체지향적으로 코드가 개선될 거라 생각하는데 어떠신가요?

2024-12-17 08:43 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/view/ConsoleReader.java
> +public class ConsoleReader implements Reader {
Read 하는 것이 콘솔이 아닌 API가 될 수도 있고 다양한 방법으로 바뀔수도 있다고 생각했습니다~

2024-12-17 08:43 UTC, hongxeob commented on java-playground/src/test/java/org/gonza/javaplayground/core/GameTest.java
> +@ExtendWith(MockitoExtension.class)
엇 이건 개인적으로 테스트해본 건데 이게 들어갔네요!

2024-12-18 03:59 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/util/Converter.java
> +    public static List<Integer> convertStringToNumberList(String input) {
숫자로 이루어진 문자열이 아닌 경우가 발생할 수 있지 않을까요?

작성자는 Validate에서 검증한다 인지할 수 있지만, 해당 함수만 봤을 때에는 오류의 가능성이 보여서요!

2024-12-18 03:59 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/view/ConsoleReader.java
> +    public String read() {
해당 함수가 withValidate이면 어떨까요? read만 갖고있는 것 같진 않아서요!

아래 함수가 오히려 read의 역할만을 수행한다 생각하는데, 어떠신가요?

2024-12-18 03:59 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +    public Game(NumberGenerator numberGenerator, Reader reader, Judgement judgement, Printer printer) {
Game의 역할에 대해서 어떻게 생각하시나요?
사용자의 입력과 출력까지의 역할을 담당하는 것으로 보이는데, 그게 옳을까라는 생각이 들어서 여쭤봅니당

2024-12-18 05:48 UTC, gyeongjae-ham requested changes

2024-12-18 05:48 UTC, gyeongjae-ham commented on java-playground/src/test/java/org/gonza/javaplayground/core/NumberGeneratorTest.java
> +    }
랜덤 숫자의 범위를 테스트하고 있는데 랜덤 숫자 값 자체를 제어해서 테스트할 수 있어야 한다고 생각하는데 어떠신가요?

2024-12-18 11:51 UTC, hongxeob commented on java-playground/src/test/java/org/gonza/javaplayground/core/NumberGeneratorTest.java
> +    }
랜덤 값 자체를 지정할 수 있어야 한다는 걸까요?
만약 그런 의미라면 제 생각으론 '랜덤'의 의미가 없어지지 않나 라는 생각이 듭니다!

2024-12-19 04:15 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +        printer.print("숫자 야구 게임을 시작합니다.");
`printer` 를 통해서 출력해달라는 메시지를 전달하는건 이해했는데 
출력에 대한 구체적인 내용까지 `Game` 이 핸들링 하는 것보다 `printer` 라고 책임을 가졌으니 
`printer` 가 이런 책임까지 처리하는 건 어떤가유?

2024-12-19 04:15 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +                if (input.equals("2")) return false;
재시작을 물어보는 로직인데 `2` 인 경우까지 판단할 필요는 없을 것 같은데 어떻게 생각하시나유? 

`1` (재시작) 인 것이 아니면 예외

2024-12-19 06:05 UTC, gyeongjae-ham commented on java-playground/src/test/java/org/gonza/javaplayground/core/NumberGeneratorTest.java
> +    }
음 그냥 랜덤인 범위를 검증하는 것보다 그걸 객체지향적으로 테스트할 때는 고정적인 값을 이끌어 낼 수 있다!! 
저 부분이 핵심인 것 같습니다!

2024-12-19 08:41 UTC, Heonbyeong commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +    public Game(NumberGenerator numberGenerator, Reader reader, Judgement judgement, Printer printer) {
(동일한 의견) 숫자 야구라는 게임 전체적인 흐름을 담당하는 부분을 의도하고 만드신 것이라고 가정했을 때, 입출력 관련 부분은 입력 담당, 출력 담당의 책임으로 분리할 수 있지 않을까요 ?

2024-12-19 08:41 UTC, Heonbyeong commented on java-playground/src/test/java/org/gonza/javaplayground/view/PrinterTest.java
UI 관련 테스트 코드는 작성하지 않아도 된다고 명시되어 있습니다 ! (참고)

2024-12-19 08:41 UTC, Heonbyeong commented on java-playground/src/test/java/org/gonza/javaplayground/core/ReaderTest.java
UI 관련 테스트 코드는 작성하지 않아도 된다고 명시되어 있습니다 ! (참고)

2024-12-28 08:29 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/Converter.java
> +    public static List<Integer> convertStringToNumberList(String input) {
해당 부분은 단순하게 숫자로 이루어진 문자열을 변환만 해주는 역할로 썼습니다!
그래서 호출하는 쪽 (사용자에게 입력 받는 부분)에서 이미 검증을 한 이후에요. 말씀주신 `숫자로된 문자열` 형태가 아닐시 그 전에 예외가 터집니다!
근데 현진님 말씀대로 이 안에서 한 번 더 검증하는 것도 맞는거 같습니다.

2024-12-28 08:32 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/view/ConsoleReader.java
> +    public String read() {
다시 메서드를 읽어보니 그게 의도가 더 명확할 듯 하네요! 굿

2024-12-28 08:34 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/core/Game.java
> +                if (input.equals("2")) return false;
GameCommand 객체를 만들어 책임을 부여해서 조금 더 명확하게 했습니다!

2025-01-08 04:06 UTC, currenjin approved these changes

2025-01-08 04:09 UTC, leeMK09 approved these changes

2025-01-08 04:48 UTC, merged