[명규] 숫자 야구
gonza-st/baseball-playground pull request #3
Opened 2024-12-15 08:21 UTC by leeMK09

- [x] 사용자가 값을 입력할 수 있다
- [x] 입력한 값이 숫자이어야 한다 
- [x] 입력한 값이 3자리 이하이어야 한다 
- [x] 컴퓨터의 숫자는 1 부터 9 사이의 서로 다른 랜덤값이어야 한다 
- [x] 입력한 값 중 같은 값이 있으면 1 볼 이다 
- [x] 입력한 값 중 같은 값이 있으며 해당 값이 같은 자리라면 1 스트라이크 이다
- [x] 같은 수가 전혀 없으면 낫싱 이다
- [x] 3개의 숫자를 모두 맞추면 게임이 종료된다 
- [x] 게임 종료 후 1 을 입력하면 게임을 재시작할 수 있다 
- [x] 게임 종료 후 2 를 입력하면 프로그램을 종료한다 
- [x] 게임 종료 후 1 혹은 2 외의 다른 값을 입력하면 예외가 발생한다

2024-12-16 07:38 UTC, hongxeob reviewed
몇가지 리뷰 남겼습니다! 테스트쪽은 명세 확인용으로만 봤어서, 메인 로직들 수정되면 테코는 그때 리뷰 남겨드리겠습니다!
고생하셨습니데이

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Answer.java
> +        return new ArrayList<>(answer);
레프리 클래스가 있는데 여기서는 각 카운트를 찾는 느낌인데 Answer라는 클래스가 굳이 필요할까요? 역할이 모호한 느낌이 듭니다!
또 메서드 호출시마다 각 객체를 생성하는 건 어떤 효과를 가져올까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Ball.java
> +    public List<Integer> findIndices(List<Integer> answer, List<Integer> number) {
Result라는 인터페이스에 `인덱스를 찾는다?` 라는 기능이 들어갈 이유가 있을까요?
-> 결과(Result)는 인덱스를 찾는다. 즉 결과가 인덱스를 찾는 객체라는 건 약간 어색한거 같아요.
만약 인덱스를 다루지 않는 게임 룰이면 어떻게 될까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Ball.java
> +        int START_INDEX = 0;
변하지 않는 값이라면 상수로 처리하는 건 어떨까요? 메서드를 호출할 때마다 해당 값을 생성할 필요가 있을까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Game.java
> +    }
Answer를 받으려면 Answer 클래스에 요청을 해서 받아야 하지 않을까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Game.java
> +    }
이것도 Game이라는 클래스에서 하는 행위라고 하기엔 조금 어색하지 않을까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Game.java
> +                return rule.getRestartFlag().equals(input);
get을 사용하는 것보다 의미있는 이름으로 캡슐화해서 호출하는건 어떨까요

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/InputParser.java
> +}
오버로딩 굿! 👍🏽

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/NumberGenerator.java
> +        Rule rule = new Rule();
메서드를 호출할 때 rule이 생성되는건 어떤 의도로 짠걸까요? NumberGenerator가 Rule 클래스에 직접적으로 의존하게 되어서 강한 결합도가 생기지 않을까요? 
또 NumberGenerator가 숫자 생성과 규칙 객체 생성 두 가지 책임을 가지게 됩니다!
또 테스트 작성에 용이할까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/NumberGenerator.java
> +        Rule rule = new Rule();
해당 클래스 + 메서드 너무 많은 책임과 역할을 가지고 있는 거 같습니다.

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Referee.java
> +    private final List<Result> orderedResultTypeList = List.of(new Strike(), new Ball());
필드 초기화? 테스트에 용이 할까요? 결합도는 어떨까요? 유연성등도 생각해보면 좋을거 같습니다.

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Referee.java
> +    }
judge 메서드에서 하는 일을 보이는대로 적어보면
1. 파서 이용한 넘버 파싱
2. 룰 이용한 길이 검증
3. 새 결과 리스트 만들기
4. 현재 답 리스트 만들기
5. 현재 숫자 리스트 만들기
6. for문 반복하기
7. 반복문 안에서 인덱스 찾기
8. 결과에 담아주기
9. 4,5번의 데이터 채워주기

너무 많은 역할을 하고 있는거 같지 않나요? 책임과 역할을 분리해서 해당 도메인의 기능을 호출해서 그 책임과 역할을 더는건 어떨까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Result.java
> +    List<Result> create(int size);
해당 인터페이스의 메서드 시그니처들을 저 두가지로 정한 이유가 있을까요? 
즉 Result가 무엇을 하는(어떤 책임을 가진) 인터페이스 인지 잘모르겠어요.

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Rule.java
> +public class Rule {
Rule?의 느낌보다 검증을 하는 느낌에 가까운데 이름이 좀 더 명확했으면 좋겠어요.
규칙! < 이건 이렇게 딱 해야해! 라는 느낌이 들어서요.

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/ui/InputView.java
> +        return scanner.nextLine();
InputView 인데 입력도 받고 출력도 하고 SRP를 위배하는거 같아요.

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/ui/InputView.java
> +}
위 리뷰와 동일합니다.

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/ui/OutputView.java
> +            return;
OutputView 인데 검증도 하는데 한가지 책임만 가진다고 할 수 있을까요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/ui/OutputView.java
> +}
얘는 내부의 private static 클래스로 설정한 이유가 있나요?

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/ui/View.java
> +    private final OutputView outputView = new OutputView();
필드 초기화..?!

2024-12-16 07:38 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/ui/View.java
> +}
View라는 좀 더 상위의 개념을 통해 Output/Input을 묶은 것 좋은거 같습니다!

2024-12-16 07:39 UTC, hongxeob requested changes
리팩토링 요먕!

2024-12-17 04:27 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Answer.java
> +        return new ArrayList<>(answer);
처음 생각은 정답 과 사용자가 입력한 값을 같은 타입이 아닌 다른 타입으로 분리해야지 
다른 개발자가 사용하기에 혼란스러울 것 같지 않아서 정의 했는데 
보니까 심판이 하는일과 비슷한 일을 하네유 

`Value` 객체로만 사용하겠슴다 변경하면 밑에 코맨트 남김유

2024-12-18 04:20 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/Client.java
> +        Game game = new Game(
한 클래스에서 너무 많은 책임을 갖고 있는 것은 아닌가 싶습니다!

2024-12-18 04:20 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Answer.java
> +    public List<Integer> findStrike(List<Integer> number) {
해당 함수는 어디서도 사용되지 않는 것으로 보이는데,, (제가 못 찾는 걸까요?)
왜 존재하나요?

2024-12-18 04:20 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Answer.java
> +    public List<Integer> findStrike(List<Integer> number) {
테스트만을 위해 생성된 함수라면 제거하는게 나아보입니다.

2024-12-18 04:20 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Referee.java
> +        return resultList.stream().allMatch(result -> result instanceof Strike);
`Referee` 가 갖고있는 역할이 너무 많은 것 같아요.
Refree에서는 결과에 대한 객체에 메시지로서 물어보는 역할을 한다면 어떨까요?

Referee는 판단을 해야지, 계산까지 할 필요는 없을 거라고 생각이 들어서요!

2024-12-18 04:20 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Rule.java
> +public class Rule {
저도 비슷하게, Rule과 Validate의 역할이 분리되어야 한다고 생각합니다.

규칙과 검증은 따로

2024-12-18 04:20 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/ui/OutputView.java
> +            System.out.println("낫싱");
Nothing의 의미를 갖는 곳이 없어보입니다.
Referee에 남긴 코멘트와 비슷하게, 의미를 담고있는 곳에 물어보는 방향은 어떨까요?

2024-12-18 04:27 UTC, gyeongjae-ham requested changes

2024-12-18 04:27 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/Client.java
> +        View view = new View();
도메인 로직이 출력에 관여하면 안될 것 같습니다!

2024-12-18 04:27 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Answer.java
> +        return new ArrayList<>(answer);
다른 관점에서 Answer에서 findStrike, findBall 을 수행하는게 맞을까? 라는 생각이 드는데 어떠세요?

2024-12-18 04:27 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Game.java
> +            }
들여쓰기 원칙에 위배되는 것 같습니다!

2024-12-18 04:27 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Game.java
> +        }
여기도 들여쓰기 두 뎁스인 것 같습니다

2024-12-18 04:27 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/domain/Game.java
> +        }
여기도 그런 것 같습니다!

2024-12-18 04:27 UTC, gyeongjae-ham commented on java-playground/src/test/java/org/gonza/javaplayground/domain/GameTest.java
> +import static org.mockito.Mockito.*;
테스트에서 mocking 하는 부분이 다 빠진 상태에서 객체지향적인 방식으로 풀어지면 어떨까요?

2024-12-18 09:25 UTC, taiyoung12 commented
너무 잘했슴다 !!

2025-01-04 08:58 UTC, hongxeob approved these changes

2025-01-08 04:07 UTC, merged