[Currenjin] Baseball
gonza-st/baseball-playground pull request #4
Opened 2024-12-16 13:41 UTC by currenjin

@gonza-st/gonza  리뷰해주십쇼 여러분들

2024-12-18 02:08 UTC, hongxeob requested changes
고생하셨습니다~ 몇가지 남겼습니다!

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
>  public class JavaPlaygroundApplication {
메인 클래스에서 너무 많은 책임을 하고 있는거 같습니다!~

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +	private static final Integer SIZE = 3;
만약 기능에 필요한 다른 Size가 생긴다면 어떻게 될까요? 조금 더 명식적이면 좋을거 같아요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/NumberConverter.java
> +		return numbers;
여기도 SRP에 위배되는 것 같아요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/NumberConverter.java
> +		for (String s : strings) {
`s` 보다는 조금 더 의미있는 명칭 어떨까요? strings도 그렇구요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +			validate(numbers);
어떤걸,어떻게 validate 한다는건지 들어가면 좋을거 같아요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		boolean start = true;
boolean 타입인데 `start` 라는 변수명을 가져가니 String ? int 같은 느낌이 들었는데, 불리언에 맞는 변수명이 좋을거 같아요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
>  	}
따로 validator 클래스를 만드는건 어떨까요?
+ 확인해보니 해당 클래스가 있는데 이건 왜 여기서 validate 하는 걸까요?!

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +			balls = new Balls(RandomNumberGenerator.generate(3, 1, 9));
3,1,9 파라미터를 처음 봤을 때 의미가 모호한거 같아요. 변하지 않는 값이라면, 매직 넘버를 의미 있는 상수로 만들어서 넣어주면 굳이 해당 메서드를 타고 확인해야하는 공수가 덜할거 같아요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +	}
메서드도 역할이 너무 많은거 같아요!

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/baseball/Ball.java
> +        return BallStatus.NOTHING;
Ball이 play를 하다?? 조금 어색한거 같아요.

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/baseball/BallStatus.java
> +	public boolean isNotNothing() {
메서드명이랑 상태가 헷갈리는거 같은데 어떤 용도일까요? (부정+부정의 의미라서 그런거 같아요)

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/RandomNumberGenerator.java
> +		Set<Integer> set = new HashSet<>();
static 메서드인데 Set은 메서드내에서 생성해주는 이유가 있을까요?

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/Validator.java
> +		return numberList.size() == numberList.stream().distinct().count();
객체지향 생활체조에 한 라인엔 한 . (점) 만 있도록 하는 것을 지향합니다!

2024-12-18 02:08 UTC, hongxeob commented on java-playground/src/test/java/org/gonza/javaplayground/baseball/BallTest.java
> +class BallTest {
모든 테스트 전반적으로 실패(예외) 케이스 테스트도 있으면 좋을거 같아요!

2024-12-18 04:45 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/util/Validator.java
> +		return numberList.size() == numberList.stream().distinct().count();
@hongxeob 여기는 stream이라서 위배되어 보이진 않는데 어떠신가요? 해당 규칙은 객체안의 객체의 기능을 끌어다가 쓰지 말라는 규칙으로 이해하고 있습니다!

2024-12-18 04:45 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/baseball/Balls.java
> +	}
Balls가 게임을 진행시키는 부분이 좀 어색하게 느껴지네요 Balls가 Ball들의 일급컬렉션이면 Balls를 가지고 게임을 진행하는 친구는 다른 친구가 아닐까요?

2024-12-18 04:45 UTC, gyeongjae-ham commented on java-playground/src/main/java/org/gonza/javaplayground/baseball/Ball.java
> +    private final int number;
오우 저는 BallNumber를 하나의 객체로 봤는데 이렇게 세분화하고 position을 가질 수도 있겠네요 👍👍👍👍👍

2024-12-18 04:45 UTC, gyeongjae-ham commented on java-playground/src/test/java/org/gonza/javaplayground/util/RandomNumberGeneratorTest.java
> +	}
랜덤성의 데이터도 제어해서 테스트할 수 있어야 한다고 생각하는데 어떠신가요?

2024-12-19 02:48 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/Validator.java
> +		return numberList.size() == numberList.stream().distinct().count();
스트림이어도 한 줄로 늘어뜨리는 것 보다, 적절하게 개행해서 체이닝 하는게 좋다고 생각합니다!
ktlint 쓸 때 파라미터에 2개 이상 들어가면 한 줄씩 분리 해주는거처럼요!

2024-12-19 03:51 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +	private static final Integer SIZE = 3;
`NUMBER_SIZE`로 변경하겠습니다 ~

2024-12-19 03:58 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		boolean start = true;
`isStarted`로 변경!

2024-12-19 04:15 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/util/RandomNumberGenerator.java
> +		Set<Integer> set = new HashSet<>();
> A collection that contains no duplicate elements. More formally, sets contain no pair of elements e1 and e2 such that e1.equals(e2), and at most one null element. As implied by its name, this interface models the mathematical set abstraction.

> 중복 요소가 없는 컬렉션입니다. 더 공식적으로, 집합에는 e1.e2와 e2가 같은 요소 쌍이 포함되지 않으며, 최대 하나의 널 요소만 포함됩니다. 이름에서 알 수 있듯이, 이 인터페이스는 수학적 집합 추상화를 모델링합니다.

중복되지 않은 수로 숫자를 `generate` 하기 위함입니다.

2024-12-19 04:29 UTC, currenjin commented on java-playground/src/main/java/org/gonza/javaplayground/util/NumberConverter.java
> +		return numbers;
어떤 측면에서 그렇게 생각하시나요?
`문자열을 숫자로 변경해주는 역할`로는 한 가지 역할만 하고있는 듯 해서요!

2024-12-26 04:36 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		if (start && result.isGameEnd(END_NUMBER)) {
이 부분은 반대에 경우에 먼저 리턴을 하고 이후에는 이미 모두 검증된 값들이 인자로 들어왔다고 가정하고 작성하는건 어떤가유?

2024-12-26 04:36 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		System.out.println("재시작 : 1");
`JavaPlaygroundApplication` 이 너무 많은 역할을 하는 것 같슴다 
- 값 출력
- 값 입력
- 값 검증
- 시작, 재시작, 종료 판단

2024-12-26 04:36 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/JavaPlaygroundApplication.java
> +		if (start && result.isGameEnd(END_NUMBER)) {
이왕 `Ball` 이라는 객체를 만들었으니 해당 객체에게 가져와달라고 하는건 어떨까유?

2024-12-26 04:36 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/baseball/Ball.java
> +        if (ball.position == this.position && ball.number == this.number) {
해당 조건문이 눈에 잘 안들어오는데 뭔가 명시적으로 읽을 수 있을만한 단계로 추상화하는건 어떤가유?

2024-12-26 04:36 UTC, leeMK09 commented on java-playground/src/main/java/org/gonza/javaplayground/baseball/PlayResult.java
> +	public void report(BallStatus ballStatus) {
`report` 메서드는 이름만 때고보면 보고서에 관련된 역할을 하는건가? 뭔가를 출력하는건가? 라는 생각을 했는데 
실제 코드는 자신의 상태를 변경하는 코드가 들어있어서 이름이 명시적으로 맞지 않는 듯 합니다

2024-12-26 04:36 UTC, leeMK09 commented on java-playground/src/test/java/org/gonza/javaplayground/baseball/BallsTest.java
> +	void _1_Ball_0_Strike() {
`BallTest` 는 "@DisplayName" 으로 테스트를 설명해줬는데 여기서는 왜 없는걸까유? 

넣을거면 넣고 안넣을거면 안넣는게 좋을 것 같슴다

2024-12-26 08:05 UTC, hongxeob commented on java-playground/src/main/java/org/gonza/javaplayground/util/NumberConverter.java
> +		return numbers;
개념적으로는 그렇지만 그 행위를 하기 위해서 스트링을 쪼개고, 반복하고 그안에서 리스트에 넣고..등등의 작업을 하고 있는거 같아요~

2025-01-04 08:58 UTC, hongxeob approved these changes

2025-01-07 01:58 UTC, merged