[병헌] 숫자야구
gonza-st/baseball-playground pull request #5
Opened 2024-12-17 15:04 UTC by Heonbyeong

후두려 패주십셔

2024-12-18 02:39 UTC, hongxeob requested changes
몇가지 코멘트 드렸습니다!

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    }
관점에 따라 다를 수 있지만, Ball이 자기 자신을 체크한다? 조금 어색한거 같아요.

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    val number: String,
궁금증 : Ball이라는 객체로까지 만들어서 관리해줘야 할 `상태`나 `행위`가 있을까요?

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +            strikeCount = strikeCount,
Ball을 체크할 때마다 ScoreBoard를 만든다?! 한번 생각해 볼 법 한 거 같아요.

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +}
객체지향이란 다른 객체들의 책임과 협력이라고 생각해요.  자기 자신을 검사하고 볼/스트라이크를 관리하는 것은 SRP를 위배하는거 같고, 응집도가 떨어지는 거 같아요.

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    private val resultView = ResultView.getInstance()
필드 주입으로 했을 때 장단점을 뭘까요? 이걸 테스트를 한다면 어떻게 주입 받아야할까요?

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +class BallPark {
BallPark? 가 무엇을 의미하는지 잘..?모르겠어요.

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
이닝이라는게 행위라는 것에 맞을까 라는 생각이 들어요.
한 이닝에 저런 행위들이 일어난다는 건 맞지만 역할을 분리할 수 있을거 같아요.
야구장의 느낌으로 간다면, 심판도 있을 것이고 등등..

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
번호를 생성하는게 야구장이 하는 걸까요?

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
힌트도 야구장이 가질 책임일까요?

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
재시작해도 되냐는 메서드는 입력값만 받아서 그값을 가지고 처리해도 되지 않을까요?
현재는 메서드 내에서 그것을 하는 행위들도 포함되어 있고 그 외에도 여러 행위가 많아 SRP를 위배하는거 같아요.

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/InputView.kt
> +    }
이건 테스트가 없나요?!

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/ResultView.kt
> +    }
이것도 테스트가 없을까요?

2024-12-18 02:39 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/ScoreBoard.kt
> +)
스코어보드가 생성될 때 값에 대한 검증은 안해도 될까요? 숫자가 아닌 다른값이 들어온다면? 마이너스 값이 들어온다면?

2024-12-18 02:40 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    val number: String,
+ 값에 대한 검증은 필요 없을까요?

2024-12-18 02:42 UTC, hongxeob commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
위 리뷰와 동일 선상으로 보면, 결국 `야구장` 이라는 큰 범주의 클래스에 다 들어간 느낌이 들어요.

2024-12-18 04:31 UTC, currenjin commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +        return false
shouldReplayGame에서 갖는 책임이 많다고 느낍니다!
객체를 관리하여 메시지를 전달하는 형태는 어떨까요?

2024-12-18 04:31 UTC, currenjin commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
++ 덧붙이자면, 해당 함수에서 갖는 역할이 많아져서 inning이라는 포괄적인 이름이 붙은 건 아닐까요?
충분히 고민하면 분리가 가능해 보입니다!

2024-12-18 04:31 UTC, currenjin commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
또한, Ball 관련 객체에서 메시지를 전달하는 형태로 분리가 가능해 보입니다!

2024-12-18 04:31 UTC, currenjin commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
GenerateNumber와 Ball은 어떤 연관이 있을지 궁금합니다!

2024-12-18 04:31 UTC, currenjin commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    fun checkBall(answer: String): ScoreBoard {
checkBall 또한 표현이 모호해 보이는데,
역할이 여러가지여서 그런 것 같습니다.

혹시 숫자가 3자리 넘어가면 어디서 검증하는지 알려주실 수 있나요? (제가 못 찾는 건가 해서..)

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    val number: String,
`number` 라는 이름을 가진 필드인데 타입이 `String` 인 것이 이상해보입니다유

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    val number: String,
이건 단순히 헷갈렸던건데 `Ball` 이라는 객체 이름만 보고 야구의 `Ball` 이라는 룰에 대한 객체인 줄 알았어유

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/InputView.kt
> +        val number = readlnOrNull().orEmpty()
`InputView` 라는 이름의 객체인데 사용자 입력과 출력이 한 곳에 있어서 구분되어있지 않은게 책임 분리가 안된 것 같아 보여요
(이건 제가 받은 코맨트 내용 중에 하나임)

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/ResultView.kt
> +        println(message)
`ResultView` 라는 이름인데 `Result` 에 대한 책임을 가지는 것 같아 보이지가 않고 그냥 단순히 인자를 받으면 출력만 하는 출력에 대한 책임만 있는 것 같아요

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +class BallPark {
저도 이름만 보고는 잘 모르겠고 안에 구현을 봐야지 무슨일을 하는지 알 것 같아요

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
저도 같은 생각임다

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    fun checkBall(answer: String): ScoreBoard {
뭔가 이름은 `checkBall` 라서 검증만 하겠구나 라고 생각했는데 결과로 `ScoreBoard` 를 건네주는게 연결되지 않네유

2024-12-18 04:47 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +            ballCount++
`check` 인데 안에서 count 를 증감하는 것 보다 명시적으로 분리하는건 어떤가유?

2024-12-18 08:41 UTC, leeMK09 commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +        val hint = createHint(ballCount = scoreBoard.ballCount, strikeCount = scoreBoard.strikeCount)
`BallPark` 에 할일이 너무 많아보이는데유 
제가 느끼기에는 해당 객체가 다른 객체에게 메시지를 보내는게 아니고 
다른 객체에게 "이거 가져와" 라고 데이터를 가져와서 자신이 다른 객체에 데이터를 핸들링 하는 느낌이 듦

2024-12-18 08:41 UTC, leeMK09 commented on heon-playground/baseball-playground/src/test/kotlin/com/gonza/heon/baseballplayground/BaseballTest.kt
> +        assertEquals(result.strikeCount, 0)
테스트 코드의 목적은 "같은수가 없으면 Nothing 을 반환한다" 라고 하는데 
그 목적에 맞게 표현되어보이지 않는데여 

제가 보기에는 "정답과 같은 수가 아무것도 없다면 볼도 아니고 스트라이크도 아니다" 라고 느껴지는데 이 의미가 Nothing 이라면 
이렇게 유추해야지 의미를 알 수 있을 거 같네유

2024-12-19 07:30 UTC, Heonbyeong commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/ResultView.kt
> +        println(message)
ResultView는 말 그대로 출력하는 객체로 들어온 입력에 대해 출력만 하면 된다고 생각합니다. UI 객체이기 때문에 출력 외에는 어떤 것도 신경쓰지 않아도 된다고 생각했습니다.

2024-12-19 07:33 UTC, Heonbyeong commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/Ball.kt
> +    fun checkBall(answer: String): ScoreBoard {
자릿수에 대한 검증은 진행하지 않고 있습니다. 해당 내용도 추가되면 좋을 것 같네유 반영하겠심더

2024-12-19 07:34 UTC, Heonbyeong commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
분리하는게 맞다고 생각합니다 ! (Ball은 값을 생성 후 가지고 있는 것이 아닌 생성된 값만을 가지고 있는다.)

2024-12-19 07:41 UTC, Heonbyeong commented on heon-playground/baseball-playground/src/main/kotlin/com/gonza/heon/baseballplayground/BallPark.kt
> +    }
야구장이라는 큰 범주를 생각하고 해당 구조를 개발한 것이 맞습니다. (실제 야구를 생각했을 때, 야구를 하며 일어나는 모든 행위를 야구장 안에 표현하기 위함) 책임과 역할을 나누었을 때 그 ```각각의 객체를 모아 응집시키는 부분이 야구장이다``` 라고 의도했습니다 ! 어떤 기준으로 책임과 역할을 나누는 것이 좋을까요 ?

2025-01-04 08:59 UTC, hongxeob approved these changes

2025-01-06 09:01 UTC, gyeongjae-ham approved these changes

2025-01-07 13:31 UTC, merged